### ISSUE TITLE
ERROR: ..."account cosmos1... does not exist"

### ISSUE THREAD

**Issue by dckc** [Agoric/cosmic-swingset#100]
When I do `SOLO_NAME=han ./docker/ag-setup-solo --pull` I just get an endless loop of error messages. The thing that sticks out to me is:

```
ag-cosmos-helper tx swingset deliver cosmos1mudm3ple5w3nf8r5zld5x6qs0zttfedhd5j6fu @/tmp/ag-solo-cosmos-deliver.2019919-1-qa9kmb.v6gor --from ag-solo -ojson --broadcast-mode block --yes --chain-id testnet-1.15.7 --output json --node tcp://206.189.130.83:26657 --home /usr/src/app/solo/han/ag-cosmos-helper-statedir
ERROR: {"codespace":"sdk","code":9,"message":"account cosmos1mudm3ple5w3nf8r5zld5x6qs0zttfedhd5j6fu does not exist"
```

but I don't know if that's the root of my problem.

[cosmic-swingset-losing.txt](https://gist.github.com/dckc/53dc1ae3942ded9b38ab17a5f379695a) is a more full transcript.

**Comment by michaelfig** [comment]
Your provisioning code has not been properly used the first time you ran `ag-setup-solo` with the `han` SOLO_NAME.  Try a different name in order to input your code.

If you did input the code that Tatyana provided you and already got a good connection, there's something different going wrong.

When you input the provisioning code and wait, then the cosmos pubkey account is initialized.  Once that's done, you can reuse the SOLO_NAME as many times as you wish: the code has registered your public key with the testnet.

**Comment by dckc** [comment]
The article said that when I did `ag-setup-solo`, it would prompt me for a code. It did not. It just spewed stuff on the screen for a long time.

**Comment by dckc** [comment]
oh. interesting. When I use a different name than `han`, I get prompted for a code.

So some state is squirreled away somewhere? Do you know where? I deleted my `cosmic-swingset` directory and did a fresh clone before reporting the problem above.

**Comment by michaelfig** [comment]
In a docker volume: `docker volume ls`

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 100
