### ISSUE TITLE
Installation problem - setup bootstrap

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#53]
`ag-setup-cosmos bootstrap` fails, apparently because of a problem communicating with Docker, but docker seems to be otherwise working

```
david@ZIENA:~/projects/cosmic-swingset (master)$ ag-setup-cosmos bootstrap
$ cd /usr/src/app/chains/agoric
$ /usr/local/bin/ag-setup-cosmos provision -auto-approve
$ terraform apply -auto-approve

Error: Error running plan: 1 error occurred:
	* module.docker1.provider.docker: Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?




error running ag-setup-cosmos: Aborted with exit code 1
david@ZIENA:~/projects/cosmic-swingset (master)$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Second command is proof the docker daemon is running

**Comment by michaelfig** [comment]
This is probably because you're running the `./docker/*` scripts (which don't come with support for contacting Docker from within Docker).  Fixing that is fairly straightforward (add `-v/var/run/docker.sock:/var/run/docker.sock` to the script's Docker parameters.

However, we should probably rearrange the README.md so that people only use the Docker scripts if they didn't build from source and are specifically trying to do scenario1 (see below).  If you really do want to use Docker images, you'll need to run `make docker-build` before using the scripts from `make docker-install`.

There are three major modes of running the whole thing:

1. either use [cosmic-workspace](/Agoric/cosmic-workspace) with Vagrant, possibly with `--provider=docker`
2. run using the scripts in docker/* (`make docker-build`, `make docker-install`)
3. run without Docker (as `build from source` describes, with no `docker-install`).

After that, you need to decide on the scenario you are running.  You almost certainly do not want the `Testnet tutorial` (scenario1) initially.  Instead, start with `scenario3` at the top of the README.md.

**Comment by DavidBruant** [comment]
I made the scenario 3 work
The problem i had was that after i did the `npm run build` ( Agoric/cosmic-swingset#52 ), i forgot to link the new binary to `/local/usr/bin`

I'm closing this issue and i keep in ming the 3 modes you listed

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 53
