### ISSUE TITLE
Documentation to write a smart contract with ERTP and run it with cosmic-swingset

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#57]

**Comment by michaelfig** [comment]
@Chris-Hibbert, @katelynsills, @warner could you please provide some hints on how you think a typical smart contract developer would work with the current stack?

**Comment by katelynsills** [comment]
Right now I believe the developer would have to submit a PR including the smart contract code and connect it to the provisioning process in some way. Is that right?

**Comment by michaelfig** [comment]
Yes, that's the abstract view.  I was hoping for a more concrete answer, maybe like how to wire an encouragementBot to `vat-demo.js`.

**Comment by DavidBruant** [comment]
> Right now I believe the developer would have to submit a PR including the smart contract code and connect it to the provisioning process in some way. Is that right?

If it understand correctly, the connection happens in [vat-demo](https://github.com/Agoric/cosmic-swingset/blob/master/lib/ag-solo/vats/vat-demo.js#L3) right now

They could send a PR or if they want to do their own thing without Agoric, they'd fork the repo and replace the vat-demo code (and the import of `@agoric/ertp/more/pixels/gallery`) to whatever is more relevant for them

> Right now

My feeling after a few days in various repos of Agoric is that a lot of relevant pieces are moving. As a consequence, it's not clear to me what is here to stay and for how long.

I'm torn between writing documentation for things as they are right now or writing documentation for how things could be
The former case is very present-oriented, but may present some convolutions in the developer experience
The latter may present a better developer experience, but it's not clear to me how much work would be needed for this experience to happen and whether this is work that's planned anyway or work that would be additional to what is already planned

**Comment by Chris-Hibbert** [comment]
If I wanted to give someone a path to being able to write new contracts in our system, I'd suggest they start by reading the description of the pixel demo, and the tests that exercise our escrow and covered call contracts. Understanding the point of the covered call gives enough context to see how it represent different parties interacting. the tests show how the parties have to call the pieces and what they have to do to verify the positions they're being offered.

I'm not sure how to introduce someone to thinking about designing interactions as multi-party contracts, but that's the next step. Once someone is able to think about some institution (auction, insurance, assurance contract, collateralized obligation) as a set of roles with pre-defined rights and obligations, then they can start to imagine them as roles in a contracted interaction, and can start to write it up  as code.

Of course, between those two stages, they'd need an introduction to Purses, Payments, Issuers, Assays, and the ContractHost, but those are lower level details compared to the big picture above about what it means to write contracts in our style.

**Comment by DavidBruant** [comment]
My next step was to study that pixel demo; it's reassuring for me to see this is your thinking as well :-)

> I'm not sure how to introduce someone to thinking about designing interactions as multi-party contracts, but that's the next step.

I think i do. Or rather, i think i know a direction for this which is "game design". 

My current thinking about a tutorial to Agoric's Smart Contracts could go this way:
- Implement games with one party 
    - maybe the contract has a fixed number like `37` that the person has to guess in order to win. 
    - maybe some other more interesting but simple (few lines of code) solo player games
- Implement games with 2 parties
    - tic-tac-toe
    - rock/paper/scisors (maybe this one is tricky because it requires to not reveal what people play before they play it, but also to "lock" their move. i need to think more about this one)
- Implement a game with 2 parties, but asymetric roles
- etc.

Then the complexity increases and people can be *gradually* exposed to more concepts like Amount/Assay/Mint/Purse/Issuer/Seat (the escrow exchange is probably here) and then gradually explain higher-level constructs like Seat-as-a-tradeable-good/hierarchical rights/etc. (probably covered call here), 

---

After studying the Pixel Demo example, my next step will be to try to write the game to guess `37` on my own and run it in cosmis-swingset and document the steps i took to get there

**Comment by erights** [comment]
I love the board game analogy for explaining smart contracts. Negotiating a contract is designing the rules of a game. The smart contract code is the code of a board manager for the game. In each state of the game, each player has a set of legal moves. The board manager enforces that only legal moves are made. A player chooses a move from the legal moves they may make. A move changes the state of the board game; in turn changing which moves are legal for the players. The board manager is otherwise passive. Only the players actually play the game.

Then the payoff for the analogy:

erights are like pieces that can be placed on the board. When a piece is off the board held by Alice, that's an eright Alice has. When Alice places a piece on the board, that is placing the eright into escrow with the contract. The piece can then only be removed by some player from the board according to the rules of the game.

See the "Smart Contracts" section of The Digital Path http://www.erights.org/talks/pisa/paper/#smart-contracts

See the "Smart Contracts as Board Games" part of https://youtu.be/oBqeDYETXME?t=3171

These explanations also suggest a more explicitly state-machine formulation of the board manager behavior than the ways we've actually been writing them. This is good, as it anticipates the direction we'll probably be moving anyway, with @katelynsills 's upcoming Scooter reformulation. Before then, even with the current code-based way of encoding state, the analogy is still helpful.

**Comment by DavidBruant** [comment]
> See the "Smart Contracts as Board Games" part of https://youtu.be/oBqeDYETXME?t=3171

Credit where it's due, this is exactly where i got the idea of games being suitable candidates for contracts :-p

**Comment by DavidBruant** [comment]
Thank you for the discussion here

I'm moving this discussion to https://github.com/Agoric/Documentation/pull/3
Closing the issue accordingly. Please reopen if i missed something in this issue that needs to be addressed

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 57
