### ISSUE TITLE
Consider not using the infix-bang syntax

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#60]
Infix-bang is [currently a stage 0 proposal](https://github.com/tc39/proposals/blob/884e2c3187385cd9987e48ef3a30727350abd514/stage-0-proposals.md)

As consequence, the point where it can be considered standard is a bit far from now (~a year?)

People who are not familiar with the JavaScript ecosystem may be confused by it

Also, it does not add a lot of value compared to what the demo would be like without it:
- `home.gallery!tapFaucet()` => `home.gallery.post('tapFaucet')`
- `home.gallery!collectFromGallery(history[10], history[16], history[15], 'my escrow')` => `home.gallery.post('collectFromGallery', [history[10], history[16], history[15], 'my escrow'])`

**Comment by michaelfig** [comment]
> As consequence, the point where it can be considered standard is a bit far from now (~a year?)

Part of Agoric's work is to help standardize it (or something like it).  So, SwingSet is a bit of a testbed for this.

> Also, it does not add a lot of value compared to what the demo would be like without it:

You have the desugaring wrong:

> * `home.gallery!tapFaucet()` => `home.gallery.post('tapFaucet')`
* `Promise.resolve(home.gallery).post('tapFaucet', [])`
> * `home.gallery!collectFromGallery(history[10], history[16], history[15], 'my escrow')` => `home.gallery.post('collectFromGallery', [history[10], history[16], history[15], 'my escrow'])`
* `Promise.resolve(home.gallery).post('collectFromGallery', [history[10], history[16], history[15], 'my escrow'])`

But where it really shines is:

* `home.gallery!tapFaucet()!getUse()!changeAllColors('red')`

which would be desugared as:

* `Promise.resolve(Promise.resolve(Promise.resolve(home.gallery).post('tapFaucet', [])).post('getUse', [])).post('changeAllColors', ['red'])`

That's more punctuation that I think anybody would reasonably want to type.  The `E()` proxy makes this less onerous, but infix bang (or its successor) is a win in my opinion.  We discussed alternatives in last week's SES meeting, but nothing else is a clear winner.

**Comment by DavidBruant** [comment]
> Part of Agoric's work is to help standardize it (or something like it). So, SwingSet is a bit of a testbed for this.

oh ok, i had missed the fact that the Pixel Demo is a demonstrator for the Infix-bang proposal, thanks for the info

> > Also, it does not add a lot of value compared to what the demo would be like without it:
> 
> You have the desugaring wrong:

I apologize, i made a mistake in my sentence. I meant "what the demo **could** be like without it", so the desugaring wasn't part of the alternative i presented

But i understand that what i suggested was irrelevant given that the Pixel Demo is meant to be a demo for the infix-bang proposal

**Comment by dtribble** [comment]
David's suggestion (and Kris Kowal's visit) inspired a variant that is a 
different place in the engineering tradeoff space: use a shorter name than
`post` and explode the arguments:

> `home.gallery.e('tapFaucet').e('getUse').e('changeAllColors', 'red')`

Here are requirements (are there others?):
1. async invocation MUST be visibly distinct from sync invocations
1. async invocation support MUST support async operations on local targets
1. async syntax SHOULD support async operations on local targets 
1. the syntax pattern SHOULD NOT obscure the actual operation being invoked
1. async method names SHOULD appear in message positions rather than as strings
1. the syntax SHOULD work for TypeScript as well as JS
1. the async invocation mechanism SHOULD correspond to the expansion of async send syntax

Requirement 3 can generally be addressed by using `Promise.resolve(target)` 
(or a shorter version like `E(target)`) on the local target. 

Here are engineering options that haven't failed on one of our MUST requirements:

| Style | Example |
| --- | --- |
| bang | `home.gallery!tapFaucet()!getUse()!changeAllColors('red')` |
| tilde | `home.gallery~tapFaucet()~getUse()~changeAllColors('red')` |
| tilde-dot | `home.gallery~.tapFaucet()~.getUse()~.changeAllColors('red')` |
| E-helper | `E(E(E(home.gallery).tapFaucet()).getUse()).changeAllColors('red')`
| post | `home.gallery.post('tapFaucet', []).post('getUse', []).post('changeAllColors', ['red'])` |
| e-post | `home.gallery.e('tapFaucet').e('getUse').e('changeAllColors', 'red')` |

Alternatives that had problems (in textual [IBIS](https://en.wikipedia.org/wiki/Issue-based_information_system) format)
```
 ? what invocation pattern should we use for async send?
   : proxy
     . Eventual references are just proxies
     . `home.gallery.tapFaucet().getUse().changeAllColors('red')`
     - Fails requirement 1
   : .e. proxy
     . Eventual references are promises with a `e` property that contains a proxy.
     . `home.gallery.e.tapFaucet().e.getUse().e.changeAllColors('red')`
     - You can store the proxy into a variable and fail requirement 1
   : bang
     - Doesn't work for TypeScript (SHOULD)
   : E-helper
     - Clumsy to get the parens right
   : e-post
     - the methodNames appear as strings
   : post
     - the methodNames appear as strings
     - the operations are hard to spot; very verbose
```

So my current preference is `tilde` with `e-post` as a fallback.

**Comment by michaelfig** [comment]
Note that the tilde alternative is actually wavy-dot, to be consistent with typescript and optional-chaining, and to prevent automatic semicolon insertion:

```
home.gallery 
   ~.tapFaucet() 
   ~.getUse()
   ~.changeAllColors('red')
```

**Comment by dtribble** [comment]
OK. I added that option above. I don't suppose `target.~methodName(args)` is a viable syntax option?

**Comment by michaelfig** [comment]
It's inconsistent with both non-null assertions and optional chaining.

**Comment by erights** [comment]
Let's go with wavy dot for now, and see how we like it. Likely, once we're used to it, it'll probably be fine.

**Comment by michaelfig** [comment]
Is infix bang out the window, then?  I will gladly update the parsers to use wavy dot, if that's the direction we'd like to take for "proposal-infix-bang".

If there's still uncertainty, I could put this behind a parser flag.  It doesn't affect anything else because the rewrite is done before any other tooling gets ahold of it.

**Comment by erights** [comment]
Infix bang is out the window. Whatever syntax we choose, if it becomes standard, typescript programmers must also be able to use it in typescript.

I don't know whether we'll come up with something we like more that wavy dot. So a flag would be fine, but low priority. Thanks.

**Comment by warner** [comment]
Wasn't there also a requirement that an adversarial object cannot cause synchronous effects when run inside this operator? I think that's what ruled out `post` and `e-post`, since the purportedly-a-Promise `home.gallery` might actually be a regular object with a `.post` method that does something surprisingly synchronous.

**Comment by michaelfig** [comment]
Closing as we are committed to tildot.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 60
