### ISSUE TITLE
In the handoff service, how can the string be shared?

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#72]
> The way to use it is to call createBoard() with a name that you share with someone else. They then call grabBoard() and pass the name you gave. If they get a valid corkboard, then you have a private channel

[(readme)](https://github.com/Agoric/cosmic-swingset/tree/7a60b03ea9baac44fb1ba9eb9f832d369fefe719#handoffservice)

I'm puzzled by "a name that you share with someone else" because this assumes an already-existing private channel. But if there exists such a channel, why the need for the corkboard?

**Comment by dtribble** [comment]
The service is for using an out-of-band channel (e.g., you are sitting with your teammates at a hackathon or are talking on the phone with a collaborator) into an in-band channel.

```
> board = home.handoff!createBoard("forDavid")
[Presence o-55]

> board!addEntry("deanKey", "davidValue")
1

> davidBoard = home.handoffService!grabBoard("forDavid")
[Presence o-55]

> davidBoard!lookup("deanKey")
"davidValue"

> stealBoard = home.handoffService!grabBoard("forDavid")
Promise.reject("Error: Entry for forDavid has already been collected.")
```
Note that the same presence number is returned for grabBoard because I'm actually the same user. If it was another user, the presence number they would see would be completely different (and unique to them).

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 72
