### ISSUE TITLE
Error in REPL following steps from the README

### ISSUE THREAD

**Issue by jfparadis** [Agoric/cosmic-swingset#83]
Following the following steps from the README:
```
px2 = home.gallery~.tapFaucet();
amt2 = px2~.getBalance();
amt2.then(a => home.gallery~.pricePixelAmount(a));
hostInvite = home.gallery~.sellToGallery(amt2);
seat = hostInvite~.host~.redeem(hostInvite~.inviteP);
```
Leads to this error:
```
Promise.reject("TypeError: o[optKey] is not a function")
```

**Comment by katelynsills** [comment]
@michaelfig is this solved with your PR? What was the issue?

**Comment by michaelfig** [comment]
Yes, it is solved by https://github.com/Agoric/SwingSet/pull/165 (but needs some help for pipelining to work correctly).  The problem was that the SwingSet promise handler tried to implement GET so that:

```js
target~.foo~.()
```

would work.  It didn't, and worse, prevented `target~.foo` from just returning a promise for the remote property lookup.

The implementation in my PR just redoes the GET handler to do remote property lookup.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 83
